echo "[1] Create a task database with CRUD operations"
echo "[2] Use OOP to design tasks as well as anything else on DEADLINES-MANAGER.xlsx"
echo "Separate task objects from taskslist script. Make two scripts, one for fast load and one for slow load. Idea: set true/false control var for speed, to avoid duplicating scripts"
echo "investigate why emojis dont display correctly"
echo "[x] <task> <time remain>"
echo "[y] <task> <time remain>"
echo "[z] Detailed variation: <index> <task> <status> <deadline> <time remaining> <location>"
echo ""