$version = "1.0" # MyTerminal version
$date = get-date -format "dddd, MMMM d, yyyy"
$time = get-date -format "hh:mm tt"
$workspace = split-path $profile -parent
$variables = "$workspace\variables.ps1" # path to variables
$aliases = "$workspace\aliases.ps1" # path to aliases
$functions = "$workspace\functions.ps1" # path to functions
$tasks = "$workspace\tasklist.ps1" # path to tasklist
$sleeptime = 60 # Set output speed for dramatic effect
$professional = "C:\Users\Ahmad\OneDrive - Algonquin College\NEXUS\PROFESSIONAL"
$myWebsite = "C:\Users\ahmad\OneDrive - Algonquin College\NEXUS\PROFESSIONAL\!PORTFOLIO\projects\website-portfolio"
$newApplication = "C:\Users\ahmad\OneDrive - Algonquin College\NEXUS\PROFESSIONAL\!PORTFOLIO\WORKSHOP\new-application"
$finalsResult = "C:\Users\Ahmad\OneDrive - Algonquin College\NEXUS\ACADEMIC\LEVEL 3\finalsResult.txt"
$downloads = "C:\Users\Ahmad\Downloads"
$trainTicket = "C:\Users\Ahmad\Downloads\Booking confirmation - VIA Rail Canada.pdf"
$market = "https://www.facebook.com/marketplace/you/selling"
$pass = "C:\Users\Ahmad\Documents\PowerShell\passwords.txt"