echo " - Create a task database with CRUD operations"
echo "- Use OOP to design tasks as well as anything else on DEADLINES-MANAGER.xlsx"
echo "- Store tasks in JSON. Iterae over task table in loading script"
echo "- Check market state > open $market"
echo "- Check OOP assignments grades > open https://brightspace.algonquincollege.com/d2l/lms/grades/my_grades/main.d2l?ou=544141"
echo "- Aide-financiere aux etudes > https://www.quebec.ca/education/aide-financiere-aux-etudes/services-ligne"
echo "- Create user-interactible navigation loop"
echo "- Toqa and Mimo math learning: `$math"
echo "     `$mathflag for bookmark"